[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asynctimer"
version = "0.1.0"
description = "Asuncio based Timer"
requires-python = ">=3.12"
